# Pegando dados de DI da B3

### Selenium

* O Selenium simula uma pessoa em um navegador.
* Cliques, logins, digitações..

In [5]:
import pandas as pd
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.chrome.options import Options
import time 
from datetime import datetime
from datetime import date

In [3]:
#options = Options()
#options.headless = True

driver = webdriver.Chrome(service=Service(ChromeDriverManager().install())) #driver da sua versão

In [3]:
driver.get('https://www.google.com.br')

In [8]:
data_di = date(2023, 10, 19)

In [10]:
data_di = data_di.strftime("%d/%m/%Y")

url = f'''https://www2.bmf.com.br/pages/portal/bmfbovespa/boletim1/SistemaPregao1.asp?
pagetype=pop&caminho=Resumo%20Estat%EDstico%20-%20Sistema%20Preg%E3o&Data={data_di}
&Mercadoria=DI1'''

In [12]:
driver.get(url)

### Pra achar elementos você deve inspecionar o site.

In [14]:
local_tabela = '''/html/body/div/div[2]/form[1]/table[3]/tbody/tr[3]/td[3]/table'''
local_indice = '''/html/body/div/div[2]/form[1]/table[3]/tbody/tr[3]/td[1]/table'''

In [16]:
elemento = driver.find_element("xpath", local_tabela)
elemento_indice = driver.find_element("xpath", local_indice)

In [18]:
html_tabela = elemento.get_attribute('outerHTML')
html_indice = elemento_indice.get_attribute('outerHTML')

In [ ]:
tabela = pd.read_html(html_tabela)[0]
indice = pd.read_html(html_indice)[0]

In [21]:
driver.quit()

### Tratamento de Dados

Meses de contratos futuros na B3

In [23]:
legenda = pd.Series(['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
                        index = ['F', 'G', 'H', 'J', 'K', 'M', 'N', 'Q', 'U', 'V', 'X', 'Z'])

In [26]:
tabela

,0,1,2,3,4,5,6,7,8,9,10
0,AJUSTE ANTER. (3),AJUSTE CORRIG. (4),PREÇO ABERT.,PREÇO MÍN.,PREÇO MÁX.,PREÇO MÉD.,ÚLT. PREÇO,AJUSTE,VAR. PTOS.,ÚLT. OF. COMPRA,ÚLT. OF. VENDA
1,"99.575,27","99.575,27",12652,12652,12658,12656,12658,"99.575,40","0,13+",12652,12658
2,"98.670,93","98.670,93",12330,12324,12334,12329,12334,"98.671,28","0,35+",12326,12336
3,"97.793,47","97.793,47",12156,12148,12166,12154,12160,"97.794,53","1,06+",12158,12160
4,"96.851,02","96.851,02",12035,12020,12035,12032,12020,"96.852,57","1,55+",12020,12030
5,"96.069,33","96.069,33",11895,11860,11895,11881,11890,"96.071,67","2,34+",11885,11890
6,"95.258,87","95.258,87",11790,11740,11795,11768,11790,"95.258,92","0,05+",11790,11795
7,"94.394,45","94.394,45",11650,11630,11665,11641,11660,"94.391,56","2,89-",11670,11700
8,"93.588,45","93.588,45",11545,11510,11560,11534,11540,"93.587,32","1,13-",11570,11600
9,"92.838,29","92.838,29",11480,11385,11500,11444,11495,"92.823,46","14,83-",11495,11500
10,"91.985,76","91.985,76",11330,11330,11405,11378,11375,"91.960,32","25,44-",11405,11445
11,"91.177,34","91.177,34",11290,11245,11365,11312,11360,"91.135,35","41,99-",11355,11395
12,"90.426,54","90.426,54",11270,11160,11315,11241,11310,"90.374,88","51,66-",11310,11325
13,"88.137,73","88.137,73",11120,11050,11245,11146,11245,"88.035,62","102,11-",11240,11245
14,"85.974,94","85.974,94",11130,11025,11240,11132,11235,"85.825,95","148,99-",11235,11250
15,"83.889,37","83.889,37",11030,10990,11240,11093,11240,"83.685,92","203,45-",11235,11240
16,"81.641,03","81.641,03",11085,11000,11265,11076,11245,"81.378,81","262,22-",11250,11270
17,"79.494,75","79.494,75",11010,10990,11270,11096,11270,"79.185,81","308,94-",11260,11270
18,"77.442,48","77.442,48",11120,11035,11325,11141,11315,"77.083,86","358,62-",0000,0000
19,"75.441,56","75.441,56",11150,11065,11370,11180,11355,"75.056,60","384,96-",11350,11375
20,"73.322,95","73.322,95",11220,11130,11415,11226,11415,"72.898,32","424,63-",0000,0000
21,"71.367,17","71.367,17",11215,11135,11450,11261,11450,"70.921,46","445,71-",11435,11450
22,"69.452,88","69.452,88",11290,11275,11500,11357,11500,"69.002,57","450,31-",0000,0000
23,"67.531,91","67.531,91",11320,11245,11555,11356,11555,"67.038,46","493,45-",11535,11570
24,"65.573,90","65.573,90",11355,11315,11600,11387,11600,"65.036,66","537,24-",0000,0000
25,"63.706,01","63.706,01",11445,11350,11660,11476,11650,"63.187,36","518,65-",11645,11670
26,"61.890,39","61.890,39",0000,0000,0000,0000,0000,"61.381,58","508,81-",0000,0000
27,"60.177,22","60.177,22",11545,11545,11670,11550,11670,"59.663,63","513,59-",0000,0000
28,"58.447,44","58.447,44",11570,11570,11705,11585,11705,"57.932,33","515,11-",0000,0000
29,"56.857,99","56.857,99",11560,11500,11800,11629,11790,"56.319,70","538,29-",11790,11800
30,"50.728,48","50.728,48",11700,11610,11900,11760,11900,"50.182,85","545,63-",11840,11920
31,"45.122,30","45.122,30",11800,11690,11990,11820,11980,"44.579,52","542,78-",11960,11990
32,"40.304,51","40.304,51",11800,11730,11990,11835,11980,"39.758,48","546,03-",0000,0000
33,"35.905,29","35.905,29",11850,11750,12040,11879,12040,"35.421,29","484,00-",12030,12040
34,"32.033,17","32.033,17",0000,0000,0000,0000,0000,"31.555,15","478,02-",0000,12090
35,"28.524,57","28.524,57",0000,0000,0000,0000,0000,"28.058,28","466,29-",0000,0000
36,"25.610,87","25.610,87",0000,0000,0000,0000,0000,"25.155,24","455,63-",0000,0000
37,"22.825,02","22.825,02",0000,0000,0000,0000,0000,"22.385,76","439,26-",0000,0000
38,"20.420,61","20.420,61",0000,0000,0000,0000,0000,"19.998,36","422,25-",0000,0000

In [28]:
tabela.columns = tabela.loc[0]

In [30]:
tabela = tabela['ÚLT. PREÇO']
tabela = tabela.drop(0, axis = 0)
tabela

1     12658
2     12334
3     12160
4     12020
5     11890
6     11790
7     11660
8     11540
9     11495
10    11375
11    11360
12    11310
13    11245
14    11235
15    11240
16    11245
17    11270
18    11315
19    11355
20    11415
21    11450
22    11500
23    11555
24    11600
25    11650
26     0000
27    11670
28    11705
29    11790
30    11900
31    11980
32    11980
33    12040
34     0000
35     0000
36     0000
37     0000
38     0000
Name: ÚLT. PREÇO, dtype: object

In [16]:
indice.columns = indice.loc[0]
indice = indice.drop(0, axis = 0)

In [17]:
tabela.index = indice['VENCTO']
tabela

VENCTO
X23    12658
Z23    12334
F24    12160
G24    12020
H24    11890
J24    11790
K24    11660
M24    11540
N24    11495
Q24    11375
U24    11360
V24    11310
F25    11245
J25    11235
N25    11240
V25    11245
F26    11270
J26    11315
N26    11355
V26    11415
F27    11450
J27    11500
N27    11555
V27    11600
F28    11650
J28     0000
N28    11670
V28    11705
F29    11790
F30    11900
F31    11980
F32    11980
F33    12040
F34     0000
F35     0000
F36     0000
F37     0000
F38     0000
Name: ÚLT. PREÇO, dtype: object

In [18]:
tabela = tabela.astype(int)
tabela = tabela[tabela != 0]
tabela = tabela/1000
tabela

VENCTO
X23    12.658
Z23    12.334
F24    12.160
G24    12.020
H24    11.890
J24    11.790
K24    11.660
M24    11.540
N24    11.495
Q24    11.375
U24    11.360
V24    11.310
F25    11.245
J25    11.235
N25    11.240
V25    11.245
F26    11.270
J26    11.315
N26    11.355
V26    11.415
F27    11.450
J27    11.500
N27    11.555
V27    11.600
F28    11.650
N28    11.670
V28    11.705
F29    11.790
F30    11.900
F31    11.980
F32    11.980
F33    12.040
Name: ÚLT. PREÇO, dtype: float64

In [19]:
lista_datas = []

for indice in tabela.index:

        letra = indice[0]
        ano = indice[1:3]

        mes = legenda[letra]

        data = f"{mes}-{ano}"

        data = datetime.strptime(data, "%b-%y")

        lista_datas.append(data)
        
tabela.index = lista_datas  

tabela = tabela/100
tabela

2023-11-01    0.12658
2023-12-01    0.12334
2024-01-01    0.12160
2024-02-01    0.12020
2024-03-01    0.11890
2024-04-01    0.11790
2024-05-01    0.11660
2024-06-01    0.11540
2024-07-01    0.11495
2024-08-01    0.11375
2024-09-01    0.11360
2024-10-01    0.11310
2025-01-01    0.11245
2025-04-01    0.11235
2025-07-01    0.11240
2025-10-01    0.11245
2026-01-01    0.11270
2026-04-01    0.11315
2026-07-01    0.11355
2026-10-01    0.11415
2027-01-01    0.11450
2027-04-01    0.11500
2027-07-01    0.11555
2027-10-01    0.11600
2028-01-01    0.11650
2028-07-01    0.11670
2028-10-01    0.11705
2029-01-01    0.11790
2030-01-01    0.11900
2031-01-01    0.11980
2032-01-01    0.11980
2033-01-01    0.12040
Name: ÚLT. PREÇO, dtype: float64